version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: quay

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Build docker images"
          command: |
            VTAG="$(git describe --tags --long)"
            echo 'colour = "blue"' > colour.py
            docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:blue-${VTAG} .
            echo 'colour = "green"' > colour.py
            docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:green-${VTAG} .

      - deploy:
          name: "Upload containers to registry"
          command: |
            set -eu
            if [ "$CIRCLE_BRANCH" = "master" ]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY
                VTAG="$(git describe --tags --long)"
                docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:blue-${VTAG}
                docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:green-${VTAG}
            fi
