version: 2.1
orbs:
  skedulo: skedulo/ci@0.5.5

parameters:
  image:
    default: skedulo/docker-debug
    type: string

jobs:
  test:
    docker:
      - image: cimg/python:3.10.0

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.14
      - checkout
      - run:
          name: Run python static analysis checks
          command: |
            pip install flake8
            flake8

workflows:
  everything:
    jobs:
      - test
      - skedulo/build_and_push_image:
          name: build_image_<<matrix.executor>>_blue
          context:
            - aws-ecr
            - prisma
          after_checkout:
            - run: echo 'colour="blue"' > colour.py
          matrix:
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          tag: blue-${VERSION_TAG}
          extra_build_args: --build-arg VERSION=${VERSION_TAG} --build-arg COLOR=blue
          push: false
          use_buildkit: true
          filters:
            branches:
              ignore:
                - main
          requires:
            - test

      - skedulo/build_and_push_image:
          name: build_and_push_image_<<matrix.executor>>_blue
          context:
            - aws-ecr
            - prisma
          after_checkout:
            - run: echo 'colour="blue"' > colour.py
          matrix:
            alias: build_and_push_image_blue
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          tag: blue-${VERSION_TAG}
          extra_build_args: --build-arg VERSION=${VERSION_TAG} --build-arg COLOR=blue
          use_buildkit: true
          filters:
            branches:
              only:
                - main
          requires:
            - test

      - skedulo/create_and_push_manifest:
          name: create_and_push_manifest_blue
          context: aws-ecr
          images: <<pipeline.parameters.image>>:blue-${VERSION_TAG}-amd64,<<pipeline.parameters.image>>:blue-${VERSION_TAG}-arm64
          manifest: <<pipeline.parameters.image>>
          tag: blue-${VERSION_TAG}
          requires:
            - build_and_push_image_blue

      - skedulo/build_and_push_image:
          name: build_image_<<matrix.executor>>_green
          context:
            - aws-ecr
            - prisma
          after_checkout:
            - run: echo 'colour="green"' > colour.py
          matrix:
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          tag: green-${VERSION_TAG}
          extra_build_args: --build-arg VERSION=${VERSION_TAG} --build-arg COLOR=green
          push: false
          use_buildkit: true
          filters:
            branches:
              ignore:
                - main
          requires:
            - test

      - skedulo/build_and_push_image:
          name: build_and_push_image_<<matrix.executor>>_green
          context:
            - aws-ecr
            - prisma
          after_checkout:
            - run: echo 'colour="green"' > colour.py
          matrix:
            alias: build_and_push_image_green
            parameters:
              executor:
                - skedulo/amd64
                - skedulo/arm64
          image: <<pipeline.parameters.image>>
          extra_build_args: --build-arg VERSION=${VERSION_TAG} --build-arg COLOR=green
          tag: green-${VERSION_TAG}
          use_buildkit: true
          filters:
            branches:
              only:
                - main
          requires:
            - test

      - skedulo/create_and_push_manifest:
          name: create_and_push_manifest_green
          context: aws-ecr
          images: <<pipeline.parameters.image>>:green-${VERSION_TAG}-amd64,<<pipeline.parameters.image>>:green-${VERSION_TAG}-arm64
          manifest: <<pipeline.parameters.image>>
          tag: green-${VERSION_TAG}
          requires:
            - build_and_push_image_green
